name: The IIITV blog
description: Blog maintained by IIITV students
meta_description: "Blog maintained by IIITV students"

markdown: redcarpet
highlighter: null
logo: false
paginate: 15
baseurl: /
domain_name: 'http://iiitv.github.io'
permalink: /:year/:month/:day/:title
google_analytics: ''

# Details for the RSS feed generator
url:            'http://iiitv.github.io'
author:         'IIITV'
